// React/src/components/Courses.jsx
import React, { useEffect, useState } from 'react';
import { courseApi } from '../api';
import EditModal from './common/EditModal.jsx';
import '../styles/components/courses.css';

export default function Courses(){
  const [courses, setCourses] = useState([]);
  const [form, setForm] = useState({ name:'', teacher:'' });
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState('');

  useEffect(()=>{ fetchAll(); }, []);

  async function fetchAll(){
    try{ const res = await courseApi.get('/all'); setCourses(res.data || []); }catch(e){ setCourses([]); }
  }

  async function createCourse(e){
    e.preventDefault();
    try{
      const res = await courseApi.post('/create', form);
      setCourses(prev => [...prev, res.data]);
      setForm({ name:'', teacher:'' });
    }catch(e){ alert('Error al crear curso'); }
  }

  async function deleteCourse(id){
    if(!window.confirm('¿Eliminar curso?')) return;
    try{ await courseApi.delete('/delete/' + id); setCourses(prev => prev.filter(c => c.id !== id)); }catch(e){ alert('Error al eliminar'); }
  }

  function openEdit(c){ setEditing(c); }

  async function handleUpdate(id, updated){
    try{ await courseApi.put('/update/' + id, updated); setCourses(prev => prev.map(p => p.id === id ? {...p, ...updated} : p)); setEditing(null); }catch(e){ alert('Error al actualizar'); }
  }

  const visible = courses.filter(c => {
    if(!search) return true;
    const q = search.toLowerCase();
    return (c.name||'').toLowerCase().includes(q) || (c.teacher||'').toLowerCase().includes(q);
  });

  return (
    <div className="container py-4">
      <h2 className="text-center" style={{fontWeight:800}}>Gestión de Cursos</h2>

      <div className="card card-common p-4 mt-3">
        <h5>Crear Curso</h5>
        <form onSubmit={createCourse}>
          <div className="row">
            <div className="col-md-6 mb-2">
              <input className="form-control" placeholder="Nombre del Curso" value={form.name} onChange={e=>setForm({...form, name:e.target.value})} required />
            </div>
            <div className="col-md-6 mb-2">
              <input className="form-control" placeholder="Profesor del Curso" value={form.teacher} onChange={e=>setForm({...form, teacher:e.target.value})} />
            </div>
            <div className="col-12">
              <button className="btn btn-primary">Crear</button>
            </div>
          </div>
        </form>
      </div>

      <div className="card card-common p-4 mt-4">
        <div className="d-flex justify-content-between align-items-center">
          <h5>Lista de Cursos</h5>
          <input className="form-control w-25" placeholder="Buscar..." value={search} onChange={e=>setSearch(e.target.value)} />
        </div>

        <div className="table-responsive mt-3">
          <table className="table">
            <thead className="table-light">
              <tr><th>ID</th><th>Nombre</th><th>Profesor</th><th>Acciones</th></tr>
            </thead>
            <tbody>
              {visible.map(c => (
                <tr key={c.id}>
                  <td>{c.id}</td>
                  <td>{c.name}</td>
                  <td>{c.teacher}</td>
                  <td>
                    <button className="btn btn-warning btn-sm me-2" onClick={()=>openEdit(c)}>Editar</button>
                    <button className="btn btn-danger btn-sm" onClick={()=>deleteCourse(c.id)}>Eliminar</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {editing && (
        <EditModal
          title="Editar Curso"
          data={editing}
          fields={[{name:'name', label:'Nombre'}, {name:'teacher', label:'Profesor'}]}
          onClose={()=>setEditing(null)}
          onSave={handleUpdate}
        />
      )}
    </div>
  );
}

// Astro/estudiantes-app/src/app/components/courses/courses.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-courses',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './courses.component.html',
  styleUrls: ['./courses.component.css']
})
export class CoursesComponent implements OnInit {
  courses: any[] = [];
  course = { id: null as number | null, name: '', teacher: '' };
  private baseUrl = environment.apiCourse;

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.loadCourses();
  }

  loadCourses() {
    this.http.get<any[]>(`${this.baseUrl}/all`).subscribe({
      next: data => this.courses = data,
      error: err => console.error('Error cargando cursos', err)
    });
  }

  saveCourse() {
    const payload = { name: this.course.name, teacher: this.course.teacher };

    if (this.course.id) {
      this.http.put(`${this.baseUrl}/update/${this.course.id}`, payload).subscribe({
        next: () => { alert('Curso actualizado'); this.loadCourses(); this.reset(); },
        error: err => console.error('Error actualizando curso', err)
      });
    } else {
      this.http.post(`${this.baseUrl}/create`, payload).subscribe({
        next: () => { alert('Curso creado'); this.loadCourses(); this.reset(); },
        error: err => console.error('Error creando curso', err)
      });
    }
  }

  editCourse(c: any) {
    this.course = { id: c.id, name: c.name, teacher: c.teacher };
  }

  deleteCourse(id: number) {
    if (confirm(`¿Eliminar curso ${id}?`)) {
      this.http.delete(`${this.baseUrl}/delete/${id}`).subscribe({
        next: () => this.loadCourses(),
        error: err => console.error('Error eliminando curso', err)
      });
    }
  }

  reset() {
    this.course = { id: null, name: '', teacher: '' };
  }
}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h2>Cursos</h2>
  <a routerLink="/" class="btn btn-outline-secondary">← Menú</a>
</div>

<div class="card p-3 mb-4 shadow-sm">
  <h5>Crear / Editar Curso</h5>
  <form (ngSubmit)="saveCourse()" class="row g-2">
    <input type="hidden" [(ngModel)]="course.id" name="id">
    <div class="col-md-6">
      <input name="name" [(ngModel)]="course.name" class="form-control" placeholder="Nombre del curso" required>
    </div>
    <div class="col-md-6">
      <input name="teacher" [(ngModel)]="course.teacher" class="form-control" placeholder="Profesor" required>
    </div>
    <div class="col-12 mt-2">
      <button class="btn btn-success me-2" type="submit"><i class="fa fa-save me-1"></i> Guardar</button>
      <button class="btn btn-secondary" type="button" (click)="reset()">Limpiar</button>
    </div>
  </form>
</div>

<div class="card shadow-sm p-3">
  <h5>Lista de Cursos</h5>
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Profesor</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let c of courses">
        <td>{{ c.id }}</td>
        <td>{{ c.name }}</td>
        <td>{{ c.teacher }}</td>
        <td>
          <button class="btn btn-sm btn-outline-primary me-1" (click)="editCourse(c)">
            <i class="fa fa-pen"></i>
          </button>
          <button class="btn btn-sm btn-outline-danger" (click)="deleteCourse(c.id)">
            <i class="fa fa-trash"></i>
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
