// React/src/components/Students.jsx
import React, { useEffect, useState } from 'react';
import { studentApi, courseApi } from '../api';
import EditModal from './common/EditModal.jsx';
import '../styles/components/students.css';

export default function Students(){
  const [students, setStudents] = useState([]);
  const [courses, setCourses] = useState([]);
  const [form, setForm] = useState({ name:'', lastName:'', email:'', courseId:'' });
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState('');

  useEffect(()=>{ fetchAll(); fetchCourses(); }, []);

  async function fetchAll(){
    try{
      const res = await studentApi.get('/all');
      setStudents(res.data || []);
    }catch(e){ console.error(e); setStudents([]); }
  }
  async function fetchCourses(){
    try{ const res = await courseApi.get('/all'); setCourses(res.data || []); }catch(e){ setCourses([]); }
  }

  async function createStudent(e){
    e.preventDefault();
    try{
      const payload = {...form, courseId: form.courseId ? Number(form.courseId) : null};
      const res = await studentApi.post('/create', payload);
      setStudents(prev => [...prev, res.data]);
      setForm({ name:'', lastName:'', email:'', courseId:'' });
    }catch(e){ alert('Error al crear estudiante'); }
  }

  async function deleteStudent(id){
    if(!window.confirm('¿Eliminar estudiante?')) return;
    try{
      await studentApi.delete('/delete/' + id);
      setStudents(prev => prev.filter(s => s.id !== id));
    }catch(e){ alert('Error al eliminar'); }
  }

  function openEdit(s){ setEditing(s); }

  async function handleUpdate(id, updated){
    try{
      await studentApi.put('/update/' + id, updated);
      setStudents(prev => prev.map(p => p.id === id ? {...p, ...updated} : p));
      setEditing(null);
    }catch(e){ alert('Error al actualizar'); }
  }

  // Search by name, lastName or email
  const visible = students.filter(s => {
    if(!search) return true;
    const q = search.toLowerCase();
    return (s.name || '').toLowerCase().includes(q) || (s.lastName||'').toLowerCase().includes(q) || (s.email||'').toLowerCase().includes(q);
  });

  return (
    <div className="container py-4">
      <h2 className="text-center" style={{fontWeight:800}}>Gestión de Estudiantes</h2>

      <div className="card card-common p-4 mt-3">
        <h5>Crear Estudiante</h5>
        <form onSubmit={createStudent}>
          <div className="row">
            <div className="col-md-6 mb-2">
              <input className="form-control" placeholder="Nombre" value={form.name} onChange={e=>setForm({...form, name:e.target.value})} required />
            </div>
            <div className="col-md-6 mb-2">
              <input className="form-control" placeholder="Apellidos" value={form.lastName} onChange={e=>setForm({...form, lastName:e.target.value})} />
            </div>
            <div className="col-12 mb-2">
              <input className="form-control" placeholder="Correo electrónico" value={form.email} onChange={e=>setForm({...form, email:e.target.value})} />
            </div>
            <div className="col-12 mb-3">
              <select className="form-control" value={form.courseId} onChange={e=>setForm({...form, courseId:e.target.value})}>
                <option value="">Seleccionar curso</option>
                {courses.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            <div className="col-12">
              <button className="btn btn-primary">Crear</button>
            </div>
          </div>
        </form>
      </div>

      <div className="card card-common p-4 mt-4">
        <div className="d-flex justify-content-between align-items-center">
          <h5>Lista de Estudiantes</h5>
          <input className="form-control w-25" placeholder="Buscar..." value={search} onChange={e=>setSearch(e.target.value)} />
        </div>

        <div className="table-responsive mt-3">
          <table className="table">
            <thead className="table-light">
              <tr>
                <th>ID</th><th>Nombre</th><th>Apellidos</th><th>Email</th><th>Curso ID</th><th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {visible.map(s => (
                <tr key={s.id}>
                  <td>{s.id}</td>
                  <td>{s.name}</td>
                  <td>{s.lastName}</td>
                  <td>{s.email}</td>
                  <td>{s.courseId}</td>
                  <td>
                    <button className="btn btn-warning btn-sm me-2" onClick={()=>openEdit(s)}>Editar</button>
                    <button className="btn btn-danger btn-sm" onClick={()=>deleteStudent(s.id)}>Eliminar</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {editing && (
        <EditModal
          title="Editar Estudiante"
          data={editing}
          fields={[
            {name:'name', label:'Nombre'},
            {name:'lastName', label:'Apellidos'},
            {name:'email', label:'Email'},
            {name:'courseId', label:'Curso ID'}
          ]}
          onClose={()=>setEditing(null)}
          onSave={handleUpdate}
        />
      )}
    </div>
  );
}

// Astro/estudiantes-app/src/app/components/students/students.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-students',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './students.component.html',
  styleUrls: ['./students.component.css']
})
export class StudentsComponent implements OnInit {
  students: any[] = [];
  courses: any[] = [];
  student = { id: null, name: '', lastName: '', email: '', courseId: null };
  searchId: number | null = null;
  private baseStudent = environment.apiStudent;
  private baseCourse = environment.apiCourse;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.loadStudents();
    this.loadCourses();
  }

  loadStudents() {
    this.http.get<any[]>(`${this.baseStudent}/all`).subscribe({
      next: data => this.students = data,
      error: err => console.error('Error cargando estudiantes', err)
    });
  }

  loadCourses() {
    this.http.get<any[]>(`${this.baseCourse}/all`).subscribe({
      next: data => this.courses = data,
      error: err => console.error('Error cargando cursos', err)
    });
  }

  saveStudent() {
    const payload = {
      name: this.student.name,
      lastName: this.student.lastName,
      email: this.student.email,
      courseId: this.student.courseId
    };

    if (this.student.id) {
      this.http.put(`${this.baseStudent}/update/${this.student.id}`, payload).subscribe({
        next: () => {
          alert('Estudiante actualizado correctamente');
          this.loadStudents();
          this.resetForm();
        },
        error: err => console.error('Error al actualizar estudiante', err)
      });
    } else {
      this.http.post(`${this.baseStudent}/create`, payload).subscribe({
        next: () => {
          alert('Estudiante guardado correctamente');
          this.loadStudents();
          this.resetForm();
        },
        error: err => console.error('Error al guardar estudiante', err)
      });
    }
  }

  editStudent(s: any) {
    this.student = { ...s };
  }

  deleteStudent(id: number) {
    if (confirm('¿Eliminar estudiante?')) {
      this.http.delete(`${this.baseStudent}/delete/${id}`).subscribe({
        next: () => this.loadStudents(),
        error: err => console.error('Error al eliminar estudiante', err)
      });
    }
  }

  searchStudent() {
    if (this.searchId) {
      this.http.get<any>(`${this.baseStudent}/${this.searchId}`).subscribe({
        next: s => this.students = s ? [s] : [],
        error: err => console.error('Error al buscar estudiante', err)
      });
    } else {
      this.loadStudents();
    }
  }

  resetForm() {
    this.student = { id: null, name: '', lastName: '', email: '', courseId: null };
  }

  getCourseName(courseId: number): string {
    const course = this.courses.find(c => c.id === courseId);
    return course ? course.name : '—';
  }
}
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Estudiantes</h2>
    <a routerLink="/" class="btn btn-outline-secondary">← Menú</a>
  </div>

  <div class="card p-3 mb-4">
    <h5>Crear / Editar estudiante</h5>
    <form (ngSubmit)="saveStudent()" #f="ngForm" class="row g-2">
      <input type="hidden" [(ngModel)]="student.id" name="id">
      <div class="col-md-3">
        <input name="name" [(ngModel)]="student.name" class="form-control" placeholder="Nombre" required>
      </div>
      <div class="col-md-3">
        <input name="lastName" [(ngModel)]="student.lastName" class="form-control" placeholder="Apellido" required>
      </div>
      <div class="col-md-3">
        <input name="email" [(ngModel)]="student.email" type="email" class="form-control" placeholder="Email" required>
      </div>
      <div class="col-md-3">
        <select name="courseId" [(ngModel)]="student.courseId" class="form-select" required>
          <option [ngValue]="null">Seleccione un curso</option>
          <option *ngFor="let c of courses" [ngValue]="c.id">{{ c.name }}</option>
        </select>
      </div>
      <div class="col-12 mt-2">
        <button class="btn btn-primary me-2" [disabled]="!f.form.valid">Guardar</button>
        <button type="button" class="btn btn-secondary" (click)="resetForm()">Limpiar</button>
      </div>
    </form>
  </div>

  <div class="card p-3">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5>Lista de estudiantes</h5>
      <div>
        <input [(ngModel)]="searchId" class="form-control d-inline-block" style="width:140px" placeholder="Buscar por ID">
        <button (click)="searchStudent()" class="btn btn-outline-primary ms-2">Buscar</button>
      </div>
    </div>

    <table class="table table-striped">
      <thead><tr><th>ID</th><th>Nombre</th><th>Apellido</th><th>Email</th><th>Curso</th><th>Acciones</th></tr></thead>
      <tbody>
        <tr *ngFor="let s of students">
          <td>{{ s.id }}</td>
          <td>{{ s.name }}</td>
          <td>{{ s.lastName }}</td>
          <td>{{ s.email }}</td>
          <td>{{ getCourseName(s.courseId) }}</td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" (click)="editStudent(s)"><i class="fa fa-pen"></i></button>
            <button class="btn btn-sm btn-outline-danger" (click)="deleteStudent(s.id)"><i class="fa fa-trash"></i></button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
